### ISSUE TITLE
can you work on the designer

### ISSUE THREAD

**Issue by 0fan** [TienPD3/tienpd3.github.io#2]
Demo: https://www.grapecity.com/spreadjs/designer/index.html

**Comment by TienPD3** [comment]
> Demo: https://www.grapecity.com/spreadjs/designer/index.html

Yes, I using it

**Comment by 0fan** [comment]
Sorry, it seems that designer is a separate authorization, and the project does not have related js files.


same as `gc.spread.sheets.designer.all.16.2.3.min.js`

<img width="1461" alt="image" src="https://github.com/TienPD3/tienpd3.github.io/assets/10867096/c6256182-abbe-40bb-a8a6-e14c54ed9520">
