### ISSUE TITLE
Please support Designer

### ISSUE THREAD

**Issue by 0fan** [TienPD3/tienpd3.github.io#3]
Sorry, it seems that designer is a separate authorization, and the project does not have related js files.

same as `gc.spread.sheets.designer.all.16.2.3.min.js`

<img width="1461" alt="image" src="https://github.com/TienPD3/tienpd3.github.io/assets/10867096/c6256182-abbe-40bb-a8a6-e14c54ed9520">

**Comment by TienPD3** [comment]
Hi @0fan 

I don't have time to support gc.spread.sheets.designer.all.16.2.3.min.js

I'm sorry
